# Generated by Django 4.1.1 on 2022-09-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='url',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='host',
        ),
    ]
